# Generated by Django 4.2.2 on 2023-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple_project',
            old_name='firstname',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='simple_project',
            name='lastname',
        ),
        migrations.AddField(
            model_name='simple_project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
